"""
M16 — Narrative Insight Layer.

Turns the measured signals into sentences a clinician can read in thirty
seconds, with a timestamp against every claim.

The rule every sentence in this module obeys:

    Report the measurement. Never report the inference.

So the output says "vocal pitch variability ran 2 SD below this client's
baseline in the second half" and never "the client sounded depressed". It says
"turn length halved after minute 30" and never "the client disengaged". The
difference matters because the first is a fact the supervisor can verify by
watching, and the second is a judgement the system is not entitled to make.

This is also why the layer is template-driven rather than generated by a
language model. Every sentence traces to a specific number through code a
reviewer can read, nothing can be hallucinated, and the same inputs always
produce the same note — which is what makes it usable as a clinical record.

The narration is written for post-session review, not live alerting. A
therapist watching a screen for notifications is not watching the client, and
attunement is the skill the whole session depends on.
"""

from __future__ import annotations

from typing import Any

from .features import DIMENSIONS

DIM_WORDS = {
    "self_agency": "sense of agency",
    "future_orientation": "future orientation",
    "emotional_granularity": "precision in naming feelings",
    "problem_ownership": "ownership of the problem",
    "reflection_depth": "depth of reflection",
}

DIM_CONCRETE = {
    "self_agency": ("more language of choosing and deciding",
                    "more language of things happening to them"),
    "future_orientation": ("more talk of what comes next",
                           "more replaying of what already happened"),
    "emotional_granularity": ("more specific emotion words",
                              "more undifferentiated feeling words such as 'bad' or 'fine'"),
    "problem_ownership": ("more account of their own part in it",
                          "more attribution of the difficulty to others"),
    "reflection_depth": ("more working out why things happen",
                         "more description of events without explanation"),
}


def _clock(seconds: float) -> str:
    return f"{int(seconds // 60):02d}:{int(seconds % 60):02d}"


def _pct(a: float, b: float) -> int:
    return int(round(100 * (a - b) / b)) if b else 0


# --------------------------------------------------------------------------
# session note
# --------------------------------------------------------------------------

def session_note(
    analysis: dict,
    trajectory: dict | None = None,
    acoustic: dict | None = None,
    video: dict | None = None,
    baseline: dict | None = None,
) -> dict:
    """Plain-English note for one session, assembled from whatever is available."""
    lines: list[str] = []
    flags: list[dict] = []

    score = analysis.get("score", {})
    feats = analysis.get("features", {})
    tpi = score.get("tpi")
    conf = score.get("confidence", 1.0)

    # ---- headline ----------------------------------------------------
    if tpi is not None:
        if tpi >= 58:
            lines.append(
                f"This session scored {tpi:.0f} on the progress index, above this "
                f"client's own baseline of 50."
            )
        elif tpi <= 42:
            lines.append(
                f"This session scored {tpi:.0f}, below this client's own baseline "
                f"of 50."
            )
        else:
            lines.append(
                f"This session scored {tpi:.0f}, close to this client's usual level."
            )

    if conf < 0.6:
        lines.append(
            f"Confidence is low ({conf:.0%}) — there was less client speech than "
            f"usual, so read the score cautiously."
        )
        flags.append({"kind": "low_confidence", "detail": f"confidence {conf:.0%}"})

    # ---- which dimensions moved -------------------------------------
    contrib = score.get("contributions", {})
    if contrib:
        ranked = sorted(contrib.items(), key=lambda kv: kv[1])
        low, high = ranked[0], ranked[-1]
        if high[1] > 0.6:
            up, _ = DIM_CONCRETE[high[0]]
            lines.append(
                f"The clearest movement was in {DIM_WORDS[high[0]]} — {up} than "
                f"this client usually shows."
            )
        if low[1] < -0.6:
            _, down = DIM_CONCRETE[low[0]]
            lines.append(
                f"{DIM_WORDS[low[0]].capitalize()} sat below their baseline: {down}."
            )
            flags.append({"kind": "dimension_below_baseline", "dimension": low[0]})

    # ---- talk volume -------------------------------------------------
    words = feats.get("n_client_words")
    if words and baseline and baseline.get("mean_words"):
        delta = _pct(words, baseline["mean_words"])
        if abs(delta) >= 25:
            direction = "more" if delta > 0 else "less"
            lines.append(
                f"The client spoke {abs(delta)}% {direction} than their average "
                f"({int(words)} words against a usual {int(baseline['mean_words'])})."
            )
            if delta <= -25:
                flags.append({"kind": "reduced_speech", "detail": f"{delta}%"})

    # ---- auxiliary signals -------------------------------------------
    if feats.get("hopelessness", 0) > 0.25:
        lines.append(
            "Language associated with hopelessness appeared more than usual in "
            "this session."
        )
        flags.append({"kind": "hopelessness_language", "value": feats["hopelessness"]})
    if feats.get("rumination", 0) > 0.25:
        lines.append("There was more repetitive, backward-looking language than usual.")

    # ---- change-talk model, if trained -------------------------------
    ml = analysis.get("ml") or {}
    ct = ml.get("client_talk") or {}
    if ct.get("change_talk_ratio") is not None and ct.get("directional_turns", 0) >= 4:
        r = ct["change_talk_ratio"]
        lines.append(
            f"Of the turns that pointed one way or the other, {r:.0%} were change "
            f"talk ({ct['n_change']} change against {ct['n_sustain']} sustain)."
        )
        if r < 0.35:
            flags.append({"kind": "low_change_talk", "value": r})

    tb = ml.get("therapist_behaviour") or {}
    if tb.get("reflection_to_question_ratio") is not None:
        ratio = tb["reflection_to_question_ratio"]
        if ratio < 0.5:
            lines.append(
                f"The session ran question-heavy — about {ratio:.1f} reflections "
                f"for every question."
            )

    # ---- acoustic ------------------------------------------------------
    if acoustic and acoustic.get("available"):
        m = acoustic.get("session_mean", {})
        f0z = m.get("f0_cv_z")
        if isinstance(f0z, (int, float)) and abs(f0z) > 1.5:
            if f0z < 0:
                lines.append(
                    f"Pitch variability ran {abs(f0z):.1f} SD below this client's "
                    f"baseline — a flatter vocal delivery than usual for them."
                )
                flags.append({"kind": "reduced_pitch_variability", "z": round(f0z, 2)})
            else:
                lines.append(
                    f"Pitch variability ran {f0z:.1f} SD above their baseline — a "
                    f"more varied delivery than usual."
                )
        pz = m.get("pause_ratio_z")
        if isinstance(pz, (int, float)) and pz > 1.5:
            lines.append(
                f"They paused more than usual ({pz:.1f} SD above their own baseline)."
            )

    # ---- video ---------------------------------------------------------
    if video and video.get("available"):
        s = video.get("summary", {})
        if s.get("arms_crossed_ratio", 0) > 0.4:
            lines.append(
                f"Arms were folded for {s['arms_crossed_ratio']:.0%} of the "
                f"recording. This is a movement observation only, not an "
                f"interpretation — posture has many causes."
            )
        if video.get("pose_detection_rate", 1) < 0.6:
            lines.append(
                "Body was out of frame for much of the recording, so the movement "
                "tracks are unreliable for this session."
            )

    # ---- moments -------------------------------------------------------
    moments = (video or {}).get("moments") or analysis.get("moments") or []
    if moments:
        stamps = ", ".join(m.get("timestamp", _clock(m.get("t", 0))) for m in moments[:5])
        lines.append(f"Moments worth reviewing: {stamps}.")

    # ---- trajectory ----------------------------------------------------
    if trajectory:
        mom = trajectory.get("momentum", {})
        state = mom.get("state")
        if state == "gaining":
            lines.append(
                f"Across sessions the trend is upward, about "
                f"{trajectory['recent_trend']['slope_per_session']:.1f} points per session."
            )
        elif state == "regressing":
            lines.append(
                f"Across recent sessions the index has been falling, about "
                f"{abs(trajectory['recent_trend']['slope_per_session']):.1f} points "
                f"per session. Worth raising in supervision."
            )
            flags.append({"kind": "declining_trend"})
        elif state == "plateauing":
            lines.append(
                "The index has been flat for several sessions, with little movement "
                "either way."
            )
            flags.append({"kind": "plateau"})

        cp = trajectory.get("change_point")
        if cp:
            lines.append(
                f"A shift shows up around session {cp['index'] + 1}, where the "
                f"average moved from {cp['mean_before']:.0f} to {cp['mean_after']:.0f}. "
                f"Worth asking what happened around then."
            )

    return {
        "note": " ".join(lines),
        "sentences": lines,
        "flags": flags,
        "principle": (
            "Every sentence reports a measurement, not an inference. The "
            "interpretation belongs to the clinician."
        ),
    }


def moment_captions(moments: list[dict]) -> list[dict]:
    """One readable line per flagged moment."""
    out = []
    for m in moments:
        bits = []
        if m.get("gesture_amplitude", 0) > 0:
            bits.append("movement changed sharply")
        if m.get("arms_crossed"):
            bits.append("arms folded")
        out.append({
            "timestamp": m.get("timestamp", _clock(m.get("t", 0))),
            "caption": (
                f"At {m.get('timestamp', _clock(m.get('t', 0)))}, "
                + (" and ".join(bits) if bits else "several tracks shifted together")
                + ". Worth watching."
            ),
        })
    return out
